package slox

// Auto-generated by GenerateAst tool

sealed trait Expr:
  def accept[R](visitor: Expr.Visitor[R]): R

object Expr:
  trait Visitor[R]:
    def visitTernaryExpr(expr: Ternary): R
    def visitBinaryExpr(expr: Binary): R
    def visitGroupingExpr(expr: Grouping): R
    def visitLiteralExpr(expr: Literal): R
    def visitUnaryExpr(expr: Unary): R

  case class Ternary(condition: Expr, ifOperator: Token, thenExpr: Expr, elseOperator: Token, elseExpr: Expr) extends Expr:
    def accept[R](visitor: Expr.Visitor[R]): R =
      visitor.visitTernaryExpr(this)

  case class Binary(left: Expr, operator: Token, right: Expr) extends Expr:
    def accept[R](visitor: Expr.Visitor[R]): R =
      visitor.visitBinaryExpr(this)

  case class Grouping(expression: Expr) extends Expr:
    def accept[R](visitor: Expr.Visitor[R]): R =
      visitor.visitGroupingExpr(this)

  case class Literal(value: Any) extends Expr:
    def accept[R](visitor: Expr.Visitor[R]): R =
      visitor.visitLiteralExpr(this)

  case class Unary(operator: Token, right: Expr) extends Expr:
    def accept[R](visitor: Expr.Visitor[R]): R =
      visitor.visitUnaryExpr(this)

