package slox

// Auto-generated by GenerateAst tool

sealed trait Stmt:
  def accept[R](visitor: Stmt.Visitor[R]): R

object Stmt:
  trait Visitor[R]:
    def visitExpressionStmt(stmt: Expression): R
    def visitPrintStmt(stmt: Print): R

  case class Expression(expression: Expr) extends Stmt:
    def accept[R](visitor: Stmt.Visitor[R]): R =
      visitor.visitExpressionStmt(this)

  case class Print(expression: Expr) extends Stmt:
    def accept[R](visitor: Stmt.Visitor[R]): R =
      visitor.visitPrintStmt(this)

