version = "3.7.15"
runner.dialect = scala3

# Use significant indentation (optional braces)
rewrite.scala3.removeOptionalBraces = yes
# Don't insert 'end' markers
rewrite.scala3.insertEndMarkerMinLines = 80
